### ISSUE TITLE
Panic in interface type assertion  

### ISSUE THREAD

**Issue by matejb** [form3tech-oss/terraform-provider-form3#76]
The https://github.com/form3tech-oss/terraform-provider-form3/blob/master/api/authenticated_client.go#L135 panics although it is wrapped into seeker here https://github.com/form3tech-oss/terraform-provider-form3/blob/master/api/authenticated_client.go#L108:L114

Maybe something else is modifying the request.

Details:
```
2020-03-27T11:20:44.821Z [DEBUG] plugin.terraform-provider-form3_v0.42.0: 2020/03/27 11:20:44 [DEBUG] retrying https://URL-REMOVED
2020-03-27T11:20:44.823Z [DEBUG] plugin.terraform-provider-form3_v0.42.0: panic: interface conversion: ioutil.nopCloser is not api.ReadSeekerCloser: missing method Seek
2020-03-27T11:20:44.823Z [DEBUG] plugin.terraform-provider-form3_v0.42.0: 
2020-03-27T11:20:44.823Z [DEBUG] plugin.terraform-provider-form3_v0.42.0: goroutine 86 [running]:
2020-03-27T11:20:44.823Z [DEBUG] plugin.terraform-provider-form3_v0.42.0: github.com/form3tech-oss/terraform-provider-form3/api.NewAuthenticatedClient.func1.1(0x0, 0xc0008604e0)
2020-03-27T11:20:44.823Z [DEBUG] plugin.terraform-provider-form3_v0.42.0: github.com/giantswarm/retry-go.Do(0xc0008db300, 0xc0008db2e0, 0x2, 0x2, 0x2, 0x625)
2020-03-27T11:20:44.823Z [DEBUG] plugin.terraform-provider-form3_v0.42.0: 	/home/albert/go/pkg/mod/github.com/giantswarm/retry-go@v0.0.0-20151203102909-d78cea247d5e/retry.go:43 +0xd1
2020-03-27T11:20:44.823Z [DEBUG] plugin.terraform-provider-form3_v0.42.0: github.com/form3tech-oss/terraform-provider-form3/api.NewAuthenticatedClient.func1(0xc000868900, 0xc0006eee40, 0xc0008db388, 0x40c698)
2020-03-27T11:20:44.823Z [DEBUG] plugin.terraform-provider-form3_v0.42.0: 	/home/albert/go/src/github.com/form3tech-oss/terraform-provider-form3/api/authenticated_client.go:148 +0x162
```

**Comment by matejb** [comment]
Maybe substitute the request body rewind via seek with https://golang.org/pkg/net/http/#Request.Clone

**Comment by acroca** [comment]
Are you enabling debug mode? I've seen that error when running it with debug mode

**Comment by matejb** [comment]
Yes, it only happens if debug mode is enabled.
